export default {
  bank: {
    bankList: [
      { name: '渤海银行', imgUrl: './assets/img/bank-icon/bank_cbhb.png', letter: 'B' },
      { name: '北京银行', imgUrl: 'images/Img_bank1@2x.png', letter: 'B' },
      { name: '城市商业银行', imgUrl: './assets/img/bank-icon/chengshanghan.png', letter: 'C' },
      { name: '长沙银行', imgUrl: './assets/img/bank-icon/csyh.jpg', letter: 'C' },
      { name: '东亚银行', imgUrl: './assets/img/bank-icon/bank_bea.png', letter: 'D' },
      { name: '广发银行', imgUrl: './assets/img/bank-icon/bank_gdb.png', letter: 'G' },
      { name: '广州农村商业银行', imgUrl: './assets/img/bank-icon/gzncsyyh.jpg', letter: 'G' },
      { name: '广州银行', imgUrl: './assets/img/bank-icon/gzyh.jpg', letter: 'G' },
      { name: '华夏银行', imgUrl: './assets/img/bank-icon/bank_hxb.png', letter: 'H' },
      { name: '汇丰银行', imgUrl: './assets/img/bank-icon/hfyh.jpg', letter: 'H' },
      { name: '杭州银行', imgUrl: './assets/img/bank-icon/hzyh.jpg', letter: 'H' },
      { name: '花旗银行', imgUrl: 'images/Img_bank2@2x.png', letter: 'H' },
      { name: '徽商银行', imgUrl: 'images/Img_bank1@2x.png', letter: 'H' },
      { name: '交通银行', imgUrl: './assets/img/bank-icon/bank_bcom.png', letter: 'J' },
      { name: '江苏银行', imgUrl: './assets/img/bank-icon/bank_jsb.png', letter: 'J' },
      { name: '农村信用合作社', imgUrl: 'images/Img_bank2@2x.png', letter: 'N' },
      { name: '农村商业银行', imgUrl: './assets/img/bank-icon/nongshanghang.png', letter: 'N' },
      { name: '南京市商业银行', imgUrl: 'images/Img_bank2@2x.png', letter: 'N' },
      { name: '农信银中心', imgUrl: 'images/Img_bank1@2x.png', letter: 'N' },
      { name: '宁波银行', imgUrl: './assets/img/bank-icon/bank_nbcb.png', letter: 'N' },
      { name: '平安银行', imgUrl: './assets/img/bank-icon/bank_pab.png', letter: 'P' },
      { name: '上海浦东发展银行', imgUrl: './assets/img/bank-icon/bank_spdb.png', letter: 'S' },
      { name: '上海银行', imgUrl: 'images/Img_bank1@2x.png', letter: 'S' },
      { name: '上海农商银行', imgUrl: './assets/img/bank-icon/bank_srcb.png', letter: 'S' },
      { name: '厦门国际银行', imgUrl: 'images/Img_bank1@2x.png', letter: 'S' },
      { name: '外资银行', imgUrl: './assets/img/bank-icon/bank_scb.png', letter: 'W' },
      { name: '兴业银行', imgUrl: './assets/img/bank-icon/bank_cib.png', letter: 'X' },
      { name: '中国工商银行', imgUrl: './assets/img/bank-icon/bank_icbc.png', letter: 'Z' },
      { name: '招商银行', imgUrl: './assets/img/bank-icon/bank_cmb.png', letter: 'Z' },
      { name: '中国农业银行', imgUrl: './assets/img/bank-icon/bank_abc.png', letter: 'Z' },
      { name: '中国建设银行', imgUrl: './assets/img/bank-icon/bank_ccb.png', letter: 'Z' },
      { name: '中国银行', imgUrl: './assets/img/bank-icon/bank_boc.png', letter: 'Z' },
      { name: '中国民生银行', imgUrl: './assets/img/bank-icon/bank_cmbc.png', letter: 'Z' },
      { name: '中国邮政储蓄', imgUrl: './assets/img/bank-icon/bank_psbc.png', letter: 'Z' },
      { name: '中信银行', imgUrl: './assets/img/bank-icon/bank_citic.png', letter: 'Z' },
      { name: '中国光大银行', imgUrl: './assets/img/bank-icon/bank_ceb.png', letter: 'Z' },
      { name: '浙商银行', imgUrl: 'images/Img_bank1@2x.png', letter: 'Z' },
    ],
  },
};

